data <- read.table("household_power_consumption.txt", header = TRUE, sep = ";", na.strings = "?")
data07 <- rbind(data[data$Date == "1/2/2007",], data[data$Date == "2/2/2007",])
data07$Date <- as.Date(data07$Date, "%d/%m/%Y")
data07 <- cbind(data07, "Datetime07" = as.POSIXct(paste(data07$Date, data07$Time)))
par(mfrow=c(2,2))
plot(data07$Global_active_power~data07$Datetime07, type="l")
plot(data07$Voltage~data07$Datetime07, type= "l")
with(data07, {plot(Sub_metering_1~Datetime07, type = "l")})
lines(data07$Sub_metering_2~data07$Datetime07, col = "red")
lines(data07$Sub_metering_3~data07$Datetime07, col = "Blue")
plot(data07$Global_reactive_power~data07$Datetime07, type = "l")
dev.copy(png, file = "plot4.png", height = 480, width = 480)
dev.off()
